package net.tilera.materialapi.recipes;

import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.oredict.ShapedOreRecipe;
import net.minecraftforge.oredict.ShapelessOreRecipe;
import net.tilera.materialapi.items.Ingots;
import net.tilera.materialapi.items.Nuggets;

public class NuggetRecipes {

	public static void init() {
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Items.IRON_INGOT), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetIron));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetIron, 9), Items.IRON_INGOT));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingot1810ium), "NNN", "NNN", "NNN", 'N', Nuggets.nugget1810ium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nugget1810ium, 9), Ingots.ingot1810ium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotAdvancedAlloy), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetAdvancedAlloy));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetAdvancedAlloy, 9), Ingots.ingotAdvancedAlloy));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotAlubrass), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetAlubrass));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetAlubrass, 9), Ingots.ingotAlubrass));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotAluminum), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetAluminum));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetAluminum, 9), Ingots.ingotAluminum));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotArdite), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetArdite));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetArdite, 9), Ingots.ingotArdite));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotBedrock), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetBedrock));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetBedrock, 9), Ingots.ingotBedrock));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotBedrockium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetBedrockium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetBedrockium, 9), Ingots.ingotBedrockium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotBluestone), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetBluestone));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetBluestone, 9), Ingots.ingotBluestone));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotBlutonium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetBlutonium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetBlutonium, 9), Ingots.ingotBlutonium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotBrass), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetBrass));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetBrass, 9), Ingots.ingotBrass));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotBronze), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetBronze));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetBronze, 9), Ingots.ingotBronze));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotChaos), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetChaos));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetChaos, 9), Ingots.ingotChaos));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotChrome), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetChrome));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetChrome, 9), Ingots.ingotChrome));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotCobalt), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetCobalt));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetCobalt, 9), Ingots.ingotCobalt));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotConstantan), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetConstantan));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetConstantan, 9), Ingots.ingotConstantan));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotCopper), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetCopper));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetCopper, 9), Ingots.ingotCopper));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotCosmicNeutronium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetCosmicNeutronium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetCosmicNeutronium, 9), Ingots.ingotCosmicNeutronium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotCreativite), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetCreativite));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetCreativite, 9), Ingots.ingotCreativite));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotCrystalMatrix), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetCrystalMatrix));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetCrystalMatrix, 9), Ingots.ingotCrystalMatrix));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotCyanite), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetCyanite));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetCyanite, 9), Ingots.ingotCyanite));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotDarkSteel), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetDarkSteel));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetDarkSteel, 9), Ingots.ingotDarkSteel));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotDemon), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetDemon));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetDemon, 9), Ingots.ingotDemon));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotDraconic), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetDraconic));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetDraconic, 9), Ingots.ingotDraconic));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotDraconium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetDraconium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetDraconium, 9), Ingots.ingotDraconium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotDragonEgg), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetDragonEgg));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetDragonEgg, 9), Ingots.ingotDragonEgg));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotElectricalSteel), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetElectricalSteel));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetElectricalSteel, 9), Ingots.ingotElectricalSteel));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotElectrum), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetElectrum));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetElectrum, 9), Ingots.ingotElectrum));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotEnchanted), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetEnchanted));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetEnchanted, 9), Ingots.ingotEnchanted));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotEnder), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetEnder));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetEnder, 9), Ingots.ingotEnder));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotEnderium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetEnderium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetEnderium, 9), Ingots.ingotEnderium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotEndgameium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetEndgameium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetEndgameium, 9), Ingots.ingotEndgameium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotEnergeticAlloy), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetEnergeticAlloy));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetEnergeticAlloy, 9), Ingots.ingotEnergeticAlloy));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotEvilInfused), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetEvilInfused));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetEvilInfused, 9), Ingots.ingotEvilInfused));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotGlowstone), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetGlowstone));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetGlowstone, 9), Ingots.ingotGlowstone));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotGraphite), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetGraphite));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetGraphite, 9), Ingots.ingotGraphite));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotGreenstone), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetGreenstone));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetGreenstone, 9), Ingots.ingotGreenstone));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotInfinity), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetInfinity));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetInfinity, 9), Ingots.ingotInfinity));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotInvar), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetInvar));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetInvar, 9), Ingots.ingotInvar));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotIridium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetIridium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetIridium, 9), Ingots.ingotIridium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotKnightslime), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetKnightslime));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetKnightslime, 9), Ingots.ingotKnightslime));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotLead), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetLead));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetLead, 9), Ingots.ingotLead));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotLudicrite), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetLudicrite));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetLudicrite, 9), Ingots.ingotLudicrite));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotLumium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetLumium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetLumium, 9), Ingots.ingotLumium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotManyullyn), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetManyullyn));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetManyullyn, 9), Ingots.ingotManyullyn));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotMithril), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetMithril));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetMithril, 9), Ingots.ingotMithril));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotNickel), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetNickel));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetNickel, 9), Ingots.ingotNickel));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotObsidian), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetObsidian));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetObsidian, 9), Ingots.ingotObsidian));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotOsmium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetOsmium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetOsmium, 9), Ingots.ingotOsmium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotPhasedGold), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetPhasedGold));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetPhasedGold, 9), Ingots.ingotPhasedGold));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotPigiron), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetPigiron));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetPigiron, 9), Ingots.ingotPigiron));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotPlatinum), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetPlatinum));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetPlatinum, 9), Ingots.ingotPlatinum));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotQuartzEnriched), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetQuartzEnriched));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetQuartzEnriched, 9), Ingots.ingotQuartzEnriched));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotRedstone), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetRedstone));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetRedstone, 9), Ingots.ingotRedstone));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotRedstoneAlloy), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetRedstoneAlloy));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetRedstoneAlloy, 9), Ingots.ingotRedstoneAlloy));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotRefinedObsidian), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetRefinedObsidian));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetRefinedObsidian, 9), Ingots.ingotRefinedObsidian));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotSignalum), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetSignalum));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetSignalum, 9), Ingots.ingotSignalum));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotSilver), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetSilver));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetSilver, 9), Ingots.ingotSilver));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotSoularium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetSoularium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetSoularium, 9), Ingots.ingotSoularium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotStarSteel), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetStarSteel));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetStarSteel, 9), Ingots.ingotStarSteel));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotSteel), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetSteel));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetSteel, 9), Ingots.ingotSteel));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotTheingot), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetTheingot));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetTheingot, 9), Ingots.ingotTheingot));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotTin), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetTin));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetTin, 9), Ingots.ingotTin));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotTitanium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetTitanium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetTitanium, 9), Ingots.ingotTitanium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotTungsten), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetTungsten));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetTungsten, 9), Ingots.ingotTungsten));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotTungstenSteel), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetTungstenSteel));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetTungstenSteel, 9), Ingots.ingotTungstenSteel));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotUnstable), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetUnstable));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetUnstable, 9), Ingots.ingotUnstable));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotUranium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetUranium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetUranium, 9), Ingots.ingotUranium));
		GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(Ingots.ingotYellorium), "NNN", "NNN", "NNN", 'N', Nuggets.nuggetYellorium));
		GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(Nuggets.nuggetYellorium, 9), Ingots.ingotYellorium));
	}
}
